# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityinfodetail',
            name='description',
            field=models.CharField(default='  ', max_length=128),
        ),
        migrations.AddField(
            model_name='cityinfodetail',
            name='picture',
            field=models.ImageField(blank=True, upload_to='thumbnail_images'),
        ),
        migrations.AddField(
            model_name='cityinfodetail',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
