# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-25 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityinfodetail',
            name='googlekey',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='NULL', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='NULL', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.IntegerField(default=0),
        ),
    ]
