# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0002_auto_20171023_1134'),
        ('findr', '0002_auto_20171025_1803'),
    ]

    operations = [
    ]
