# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-23 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Tourist'), ('3', 'Businessman')], default='', max_length=128),
        ),
    ]
